### ISSUE TITLE
Convert to Go

### ISSUE THREAD

**Issue by jaredallard** [stegmanh/snake#1]
While typescript is cool, you could really enhance the performance of this application by writing it in Go and using wasm to compile it to webassembly

**Comment by j-crowe** [comment]
bump

**Comment by stegmanh** [comment]
@jaredallard @j-crowe Until a JS based neural network can achieve full Turing completeness, I'm afraid this project can not progress any further. Happy to accept PRs though

**Comment by jaredallard** [comment]
hi, PR submitted, please review when able, thanks

**Comment by jaredallard** [comment]
i no longer need this, so long and thankssssss for all the fish
